services:
    hone_solutions_back_new:
        build: .
        user: 'root'
        container_name: 'hone_solutions_back_new'
        ports:
          - "7001:8080"
        volumes:
          - .:/app
        networks:
            - local_net
        stdin_open: true
        tty: true
networks:
    local_net:
        name: local_net
        driver: bridge
        external: true
