services:
    hs_backend:
        image: node:18.19.1
        user: 'root'
        container_name: 'hs_backend'
        ports:
          - "7001:7001"
        volumes:
          - .:/app
        working_dir: /app
        networks:
            - local_net
        stdin_open: true
        tty: true
        command: npm run watch
networks:
    local_net:
        name: local_net
        driver: bridge
        external: true
